<?php
// Generated by Rawr 1.0

namespace Enterprise\HumanResources {
  interface IEmployer {
    public function work(string $fromTime, string $toTime);
  }
  class Employer implements IEmployer {
    public function __construct(string $name)
    {
    }
    public function work(string $fromTime, string $toTime)
    {
    }
  }
}
?>
