<?php
// Generated by Rawr 1.0

namespace RawrLang\Lexer {
  use \Type\String;
  use \Type\Integer;
  interface IHuman{
    public function walk(Integer $&n, \Ambient\Capy $&until);
  }
  class Human implements IHuman {
    private $steps;
    public static function walk(Integer $&n, \Ambient\Capy $&until);
  }
}
?>
